export const GET_DETAILS = "GET_DETAILS";
export const ADD_DETAILS = "ADD_DETAILS";
export const UPDATE_DETAILS = "UPDATE_DETAILS";
export const DELETE_DETAILS = "DELETE_DETAILS";
export const GET_DETAILS_ERROR = "GET_DETAILS_ERROR";
export const ADD_DETAILS_ERROR = "ADD_DETAILS_ERROR";
export const UPDATE_DETAILS_ERROR = "UPDATE_DETAILS_ERROR";
export const DELETE_DETAILS_ERROR = "DELETE_DETAILS_ERROR";
